name: Python Build Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dependabot/*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail=false: true
      matrix:
        python-version: [ '3.11' ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install application in debug mode
        pip install -r requirements/development.txt
        pip install -e .
        # builds both sdist and wheel
        python -m build --no-isolation
    - name: Configure and Run Application
      run: |
        midorianki --version
        curl https://gist.githubusercontent.com/StefanGreve/5d8d3111eb4e29bbce691f6ef2ebb656/raw/4a8b081086fa4174b64c6f86be33fb07fa36590f/kaze-no-uta-wo-kike.csv --output test.csv
        midorianki convert --file ./test.csv --name "my_deck" --dest $HOME
